spring.application.name=BeneficiaryBank

server.port=8084

upi.baseUrl=http://localhost:8081/upi

psp.orgId=158888

# how often to send HBT (3 minutes)
psp.hbt.interval.ms=180000
psp.hbt.initialDelay.ms=10000
psp.hbt.retry.attempts=3

hbt.enabled=false
hbt.api.enabled=false

