spring.application.name=RemitterBank

server.port=8083

upi.baseUrl=http://localhost:8081/upi


upi.switch.reqhbt.base=http://localhost:8081/upi/ReqHbt/2.0/urn:txnid:

# PSP identity for routing (must match psp_bank.org_id)
psp.orgId=159999

# how often to send HBT (3 minutes)
psp.hbt.interval.ms=180000
psp.hbt.initialDelay.ms=10000
psp.hbt.retry.attempts=3

