# app identity & port (you already have)
spring.application.name=PayerPSP
server.port=8080

# Logging levels
logging.level.root=INFO
# set package(s) you want to see; change to DEBUG for more verbosity
logging.level.com.payer=INFO
logging.level.com.payer.PayerPSP.controller=DEBUG
logging.level.com.payer.PayerPSP=DEBUG

# Console log pattern (human friendly)
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n

# Write logs to a file (useful for async tests)
# logs will be created at project-root/logs/payer-app.log
logging.file.name=logs/payer-app.log
logging.file.max-size=10MB
logging.file.max-history=7


# scheduling
payer.hbt.interval.ms=180000
# where to post ReqHbt (UPISim)
upi.switch.reqhbt.base=http://localhost:8081/upi/ReqHbt/2.0/urn:txnid:
# Payer orgId ? must match psp_bank.org_id row
payer.orgId=156666


