# ===============================
# DEV - H2 IN-MEMORY DATABASE
# ===============================

spring.datasource.url=jdbc:h2:mem:upisimdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Hikari (Optional for H2)
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1


spring.sql.init.mode=always
spring.sql.init.platform=dev
spring.sql.init.schema-locations=classpath:schema.sql
spring.jpa.defer-datasource-initialization=true

