# ===============================
# DEV - H2 IN-MEMORY DATABASE
# ===============================

spring.datasource.url=jdbc:h2:mem:upisimdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Hikari (Optional for H2)
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1


spring.sql.init.mode=always
spring.sql.init.platform=dev
spring.jpa.defer-datasource-initialization=true

