spring.application.name=UPISim
server.port=8081

spring.devtools.restart.enabled=false

spring.profiles.active=dev

# Logging levels (no inline comments in values)
logging.level.root=INFO
logging.level.com.npci.UPISim=DEBUG

# Console pattern
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n

# File logging location
logging.file.name=C:/Users/kalai/OneDrive/Desktop/UPI Updated Hackathon/UPISim/logs/upi-sim.log

