-- Create transaction_logs table if it doesn't exist (H2-compatible)
CREATE TABLE IF NOT EXISTS transaction_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    txn_id VARCHAR(255),
    api VARCHAR(255),
    direction VARCHAR(50),
    uri VARCHAR(500),
    payload TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(50)
);

-- Create indexes (column names must match JPA entity: txnId, createdAt)
CREATE INDEX IF NOT EXISTS idx_transaction_logs_txn_id ON transaction_logs(txnId);
CREATE INDEX IF NOT EXISTS idx_transaction_logs_created_at ON transaction_logs(createdAt);
